### ISSUE TITLE
Package stability

### ISSUE THREAD

**Issue by IsraelOrtuno** [vanilophp/order#1]
I was looking for a package like this for Laravel and this seems to be the best looking option!

I was wondering how stable it is as I have seen some comments inside suggesting it may get changes in future.

**Comment by fulopattila122** [comment]
At the moment the features it provides is minimal, so there will be a enhancements in the next months.
But what the package does already will either not change or if there will be a BC, then we'll clearly state that in the UPGRADE doc, so you will know how to handle it.

These are the upcoming improvements:
- configurable state machine (add arbitrary order states and define transitions between them)
- more order events (like `OrderWasCancelled`, `OrderWasCompleted`, etc)
- Payment and Shipment handling (optional)
- Handling Taxes (optional)
- Handling Promotions (optional)
