### ISSUE TITLE
Create order

### ISSUE THREAD

**Issue by senol1** [vanilophp/order#7]
TypeError
Return value of Konekt\Concord\Proxies\EnumProxy::targetClass() must be of the type string, null returned
Help please !

**Comment by fulopattila122** [comment]
How do you create the order?

**Comment by senol1** [comment]
just with
use Vanilo\Order\Model\Order;

$order = Order::create([
    'number' => 'PO123456'
]);

**Comment by fulopattila122** [comment]
Looks like the installation is incomplete.

I guess you're only using the order module. If that's true, here's what you need to do:

Please add a `concord.php` file to the config/ folder with the following content:

```php
<?php

return [
    'modules' => [
        \Konekt\Address\Providers\ModuleServiceProvider::class,
        \Konekt\User\Providers\ModuleServiceProvider::class,
        \Vanilo\Order\Providers\ModuleServiceProvider::class,
    ]
];
```

I realized this part was missing from the documentation. Please let me know if it worked or if more issues arise.
